<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Login</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	<form action = "form.php" method = "post">
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Login</a></h1>
		<form id="form_41150" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Login</h2>
			<p>please enter the credentials to start voting</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Id </label>
		<div>
			<input id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_1"><small>enter id</small></p> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Password </label>
		<div>
			<input id="element_2" name="element_2" class="element text medium" type="password" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_2"><small>enter pass</small></p> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="41150" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.salabs.in">Shresth Agrawal: salabs.in</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</form>	
	</body>
</html>